apiVersion: v1
kind: Service
metadata:
  name: springboot-demo-service
spec:
  type: NodePort
  selector:
    app: springboot-demo
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007

